### ISSUE TITLE
Fraction rates

### ISSUE THREAD

**Issue by murwa** [rcbytes/angular-input-stars#11]
Hey guyz, I have a situation where i need to display a fraction rating, say 2.85. I'm thinking i can round the fractions to the nearest quatiles so i can have full, quarter, half and three-quarter stars. Any help? I could have made a pr for that but unfortunately I'm running out of time for my project

**Comment by melloc01** [comment]
hey @Murwa, that's a planned enhancement. 
By the beginning of the development I had to choose, fractions or not, I chose not.
It's a known must-have enhancement, I'm currently working on it, thank you for opening the issue

**Comment by murwa** [comment]
@rcbytes I actually implemented them in my project; maybe I can share when I'm done

**Comment by melloc01** [comment]
@Murwa, that would be so nice =D Please, do it when it's possible. ty ty

**Comment by murwa** [comment]
:+1: :ok_hand:

**Comment by yobre** [comment]
@melloc01 & @Murwa -> how do I use the half star function? In that release is this feature? thanks

**Comment by basilfarraj** [comment]
@melloc01  @murwa i also would love to know how :)
