### ISSUE TITLE
ngModel doesn't work unless controller is set 'as' something

### ISSUE THREAD

**Issue by fskeeled** [rcbytes/angular-input-stars#25]
Unless I do `ng-controller="Controller as Ctrl"` and then use it on the input as `ng-model="Ctrl.myModel"` it doesn't work.

I've tested it with `ng-model="myModel"` and the data seems to be one way only, not bi-directional. I've tested running your directive in a jsfiddle you can [view here](https://jsfiddle.net/filipetedim/14f05jdb/2/) and it simply does not run.

A possible fix for this is to add into the scope the following to the `directive` variable:
`scope: { ngModel: '='}`

**Comment by melloc01** [comment]
@filipeskeeled cool! Thanks.

Will test your suggestion!

**Comment by dacastro4** [comment]
Hello.

I'm currently having that same issue and with the latest update the `ngModel: '=' solution` still doesn't work.
