### ISSUE TITLE
Max value from scope doesn't work

### ISSUE THREAD

**Issue by fabiobsantos92** [rcbytes/angular-input-stars#29]
I'm trying to assign a dynamic value to max property using a scope var and it's not working.
Example:
Controller:
$scope.userRating=2;
$scope.maxRating=8;

View:
<input-stars max="maxRating" ng-model="userRating" on-star-click="updateRating()"></input-stars>

**Comment by melloc01** [comment]
can you try it again @fabiobsantos92?

**Comment by dacastro4** [comment]
Tested and currently it's working.

**Comment by melloc01** [comment]
cool @dacastro4 thanks for the feedback = )
