### ISSUE TITLE
Can't get "on-star-click" working

### ISSUE THREAD

**Issue by alexac1970** [rcbytes/angular-input-stars#34]
Tried your example and function set in on-star-click attribute is not called. Is it working properly? Thanks.

**Comment by melloc01** [comment]
Thanks @alexac1970 the scope visibility wasn't right for evaluating functions, thanks! :+1:

**Comment by silasrm** [comment]
Bower is outdated.

**Comment by jemliF** [comment]
I am facing the same problem here, I need to listen for user rating event and I can't get it using on-star-click neither ng-click

**Comment by melloc01** [comment]
Remember you can use this repo with npm - just have to point your dependency to Github.

Last commit (032606fbb393777c4127df4b83909265b2062d83) should have fixed it, would you guys try it out?
